# Generated by Django 4.1.3 on 2023-01-09 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additional_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerTeamEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('persons.employee',),
        ),
        migrations.CreateModel(
            name='SalesTeamEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('persons.employee',),
        ),
        migrations.CreateModel(
            name='SupportTeamEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('persons.employee',),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_last_contact', models.DateTimeField(auto_now=True)),
                ('id_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='additional_data.company')),
                ('id_last_sales_employee_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persons.salesteamemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='additional_data.company')),
                ('id_sales_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persons.salesteamemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
